#!/usr/bin/env node
const fs = require('fs');
const path = require('path');

// Simple generator: concatenates listed markdown files into docs/UNIFIED_DIRECTION_SNAPSHOT.md
const files = [
  'docs/NEW_BEARINGS.md',
  'docs/packaging_guidance.md',
  'docs/vehicle_modularity.md',
  'docs/manhours_savings.md'
];

const out = 'docs/UNIFIED_DIRECTION_SNAPSHOT.md';
let outText = '# Unified Direction Snapshot (generated)\n\nGenerated by tools/generate_book.js\n\n';
files.forEach((f) => {
  try {
    const txt = fs.readFileSync(path.join(__dirname, '..', f)).toString();
    outText += `\n\n---\n\n<!-- Source: ${f} -->\n\n`;
    outText += txt;
  } catch (err) {
    console.error('Failed to read', f, err.message);
  }
});

fs.writeFileSync(path.join(__dirname, '..', out), outText);
console.log('Wrote', out);
